name: navbar_pages
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  http:
  flutter_dropdown_search: ^0.0.4
  dropdown_search: ^5.0.3
  url_launcher: ^6.3.0
  webview_flutter: ^4.9.0
  flutter_inappwebview: ^6.1.0+1
  share_plus:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/img/logo.png
    - assets/img/
